linux-variscite: follow meta-fsl-arm to 6qp_ga release
* kernel update required to match X drivers in current meta-fsl-arm (f11936b863b794359e607ccd24e27f9a35a07f0e)

* imx7 had to be added to defconfig to fix:
  | platform-imx-dma.c:(.text+0xc074): undefined reference to `imx_ddrc_get_ddr_type'
  | platform-imx-dma.c:(.text+0xc210): undefined reference to `imx7d_ddr3_freq_change'
  | platform-imx-dma.c:(.text+0xc214): undefined reference to `imx7d_ddr3_freq_change'
  | platform-imx-dma.c:(.text+0xc2f8): undefined reference to `imx_lpddr3_freq_change'
  | platform-imx-dma.c:(.text+0xc2fc): undefined reference to `imx_lpddr3_freq_change'

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>